### ISSUE TITLE
! Undefined control sequence.

### ISSUE THREAD

**Issue by VP59m** [qualiacode/arabica#8]
Hi @periodicpoint ,
after a long time I resumed an old job written with your amazing **arabica**.
When I tried to generate a new output.pdf, the terminal returned an error to me. So I though maybe I don't remember or I made some mistake and I decided to repeat step by step your example but terminal returned the same error.
This is the code
`pandoc -s -o ./output/projectname.pdf --data-dir=/vp59m/Scrivania/arabica-master/ --filter pandoc-crossref --filter pandoc-citeproc --pdf-engine=xelatex --top-level-division=chapter --number-sections --template ./controls/arabica.latex ./core/*.md ./settings/*.yaml ./metadata/*.yaml
[WARNING] Could not parse YAML metadata at line 469 column 1: Duplicate key in mapping: Scalar (Pos {posByteOffset = 10884, posCharOffset = 10860, posLine = 395, posColumn = 0}) (SUnknown Nothing "ccicons")
Error producing PDF.
! Undefined control sequence.
l.205   \subject
`
Any idea how I could fix it?
regards Igor

**Comment by Ruhrpottpatriot** [comment]
The settings file contains multiple typos and duplicate keys. You need to manually correct that.

**Comment by VP59m** [comment]
@Ruhrpottpatriot thanks so much! You were right! I edited settings.yaml to correct that and now it works!
Really thanks again :)
regards Igor

**Comment by maehr** [comment]
@VP59m could you post your changes?

**Comment by VP59m** [comment]
Hi @maehr of course! 

obviously you have to change language and others personal settings!
[https://pastebin.com/raw/eEzCtb8z](url)
If you want to know I also needed to change the template because I had also errors when I enabled tof or tof

regards

**Comment by maehr** [comment]
> Hi @maehr of course!
> 
> obviously you have to change language and others personal settings!
> [https://pastebin.com/raw/eEzCtb8z](url)
> If you want to know I also needed to change the template because I had also errors when I enabled tof or tof
> 
> regards

I also experienced errors with the template. Your fixes to the template would be immensely helpful as well.

**Comment by VP59m** [comment]
uhm ok! I hope it could help you!
[https://pastebin.com/wHLxm6Wq](url)
Do you like to work on these pandoc related projects?

**Comment by maehr** [comment]
> uhm ok! I hope it could help you!
> [https://pastebin.com/wHLxm6Wq](url)
> Do you like to work on these pandoc related projects?

Yes I do. I am most interested in improving user friendliness of pandoc markdown > tex > pdf pipelines. I will also try to fix the default settings of this repo and make a PR.

**Comment by VP59m** [comment]
I got it. I'm glad to hear this from you. I'd like to do something similar...I love to write code in python even if I'm not expert. If you want, or if you have an idea we could talk about it...Maybe we could do something

**Comment by maehr** [comment]
Yes, of course. Let's fix arabica first and then move on to fix https://github.com/maehr/typademic which needs a complete overhaul.

**Comment by periodicpoint** [comment]
Dear @VP59m, @maehr and @Ruhrpottpatriot, thank you very much for your interest and engagement. You are right, there are some typos and the overall user-friendliness is not too good at the moment. I had no time to work on this project for the last year. I currently reify my plan to redesign the entire project. I am currently working the directory and file structure and a basic control and settings via JavasScript. The next version will be much more simple and user-friendly. This will be breaking changes, though.

**Comment by VP59m** [comment]
hi there @maehr 
after a long time I tried this latex template again but it doesn't work anymore. Could you tell me if it works for you? Your feedback would help me a lot!
regards

**Comment by maehr** [comment]
Hi @VP59m, I am not using this template anymore, but the Pandoc default with some tweaks  https://github.com/maehr/academic-pandoc-template
Unfortunately I don't have time to help you fix this template.
Best of luck
Moritz

**Comment by VP59m** [comment]
Hi @maehr , got it. I looked at your template. Is it possible to number the chapters and paragraphs? If so, I could use it! :)

regards

**Comment by maehr** [comment]
> Hi @maehr , got it. I looked at your template. Is it possible to number the chapters and paragraphs? If so, I could use it! :)
> 
> regards

I guess you can. Check https://pandoc-numbering.readthedocs.io/en/latest/numbering.html# and https://pandoc.org/MANUAL.html

Best,
Moritz

**Comment by periodicpoint** [comment]
Hi folks! I am honoured that you are giving this boilerplate a try, and I appreciate that you are helping each other so generously. My commitment certainly does not come close to yours, lately. After all, I have not touched this repository for some time due to time constraints. I hope you understand that.

@VP59m, @maehr: The use of the Pandoc defaults file is definitely the way to go: https://pandoc.org/MANUAL.html#defaults-files.

So please consider this repository outdated and unmaintained until further notice. Feel free to fork and improve it or use one of the newer and better boilerplates out there like the one from @Wandmalfarbe: [pandoc-latex-template](https://github.com/Wandmalfarbe/pandoc-latex-template).

Meanwhile, I am using a newer local version, that is relying on the Pandoc defaults file. I might manage to upgrade it soon. Until then, cheers!
